pipeline {
  agent any

  environment {
    IMAGE_NAME = "aravind2003/my-website-frontend"
    SONAR_URL = "http://localhost:9000"
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'master',
            url: 'https://github.com/Aravind162003/End-to-End-CI-CD-Pipeline'
      }
    }

    stage('Install Node Dependencies') {
      steps {
        sh 'npm install'
      }
    }

    stage('Static Code Analysis') {
      steps {
        withCredentials([string(credentialsId: 'sonar123', variable: 'SONAR_AUTH_TOKEN')]) {
          sh '''
          npx sonar-scanner \
          -Dsonar.projectKey=react-exam \
          -Dsonar.sources=. \
          -Dsonar.host.url=$SONAR_URL \
          -Dsonar.login=$SONAR_AUTH_TOKEN \
          -Dsonar.exclusions=node_modules/**,build/**
          '''
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
          dockerImage = docker.build("${IMAGE_NAME}:latest")
        }
      }
    }

    stage('Push to Docker Hub') {
      steps {
        script {
          docker.withRegistry('https://index.docker.io/v1/', 'docker') {
            dockerImage.push("latest")
          }
        }
      }
    }
  }

  post {
    success {
      echo '✅ Build, Analysis & Push Successful!'
    }
    failure {
      echo '❌ Pipeline Failed!'
    }
  }
}
